handleGHRelease: true
releaseType: java-yoshi
versioning: always-bump-minor
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 1.31.4-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.32.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.33.x
